# Generated by Django 2.1.7 on 2019-04-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='message',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
